### PR TITLE
Add a GUI to the project

### PR DESCRIPTION
**Pull request by jackos**
This adds a GUI with modifiable user input for sequence lengths and smoothing, with validation. Also expands on the heatmap by adding a color legend, and a description below it.

Had to add a `def main` to `ngram.py` in order to reuse the code, while still allowing it to be run as a script.

You can see the deployed version of the GUI here: https://ngram-gui.streamlit.app (please let me know if you don't want this up and I'll take it down).

Or a preview of the GUI below by pressing the play button:

N-gram GUI

### CODE REVIEW

**Comment by bm777** [comment]
I think, keeping the learning from the backend side will be great, especially for people who really want to dig into how the n-gram model works.

And to be honest, the day openAI released the 1st iteration of GPT, I immediately had an assumption that, the idea of GPT was based on query suggestion. A kinda, you write the word `ho`, and a function load a whole set of text, and propose the word `how` based on the most recurrent word starting with `ho`. And of course, later add the semantic or the correlation of the previous words of the query to predict the next word or complete a sub-word.

Maybe I'm wrong, someone who has C programming skills would like to dig into the code and maybe tweak the parameter and experiment. I think the GUI will keep the learning process very abstract. 

Or maybe hardcore learning -> source code. @karpathy  kudo to you :)
sweet learning with GUI. @jackos kudo to you :)

**Comment by seanbetts** [comment]
Really like this - thanks for sharing!

**Comment by nathandalal** [comment]
Thanks for this change! I am excited to follow this project. I added a section to detail how inference works for the n-gram model in a PR to your branch. You can check it out here: https://github.com/jackos/ngram/pull/1

**Comment by jackos** [comment]
Hey that's a really fantastic description of how the model works thanks @nathandalal, just have a couple requests for change based on how I've seen him review PR's on his other projects.

**Comment by karpathy** [comment]
<3 streamlit, nice!!
I have to think through the best repo structure - are these simple scripts? jupyter notebooks? streamlits? etc. possibly the main repo is just the simple code, but the `dev/` directory has a lot of "auxiliary" functionality or tools.

**Comment by seanbetts** [comment]
> <3 streamlit, nice!! I have to think through the best repo structure - are these simple scripts? jupyter notebooks? streamlits? etc. possibly the main repo is just the simple code, but the `dev/` directory has a lot of "auxiliary" functionality or tools.

I think this makes the most sense - otherwise you could end up with lots of other folders in the main repo for different functionality or tools.

**Comment by jackos** [comment]
No worries @karpathy I can move it into the `dev/gui.py` and use `sys.path.append(".")` to still reuse code in `ngram.py`, and change the readme instruction to `streamlit run dev/gui.py` if you're open to that?

**Comment by jackos** [comment]
I made those changes and tested it as working so you can see how it looks

**Comment by xihajun** [comment]
> <3 streamlit, nice!! I have to think through the best repo structure - are these simple scripts? jupyter notebooks? streamlits? etc. possibly the main repo is just the simple code, but the `dev/` directory has a lot of "auxiliary" functionality or tools.

Could create a system where students/developers submit projects related to the learning materials. To encourage participation and excellence, we could implement a rewards program and a leaderboard. This leaderboard would allow students to vote on and rank the best projects, promoting healthy competition and peer recognition.

**Pull request closed without merging**
